// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfYJcUWjv-gfNCxNZJ54rU6OhfSYNhRL0',
    appId: '1:706621538915:web:71d32b63539cc7dc452e56',
    messagingSenderId: '706621538915',
    projectId: 'companies-tasks',
    authDomain: 'companies-tasks.firebaseapp.com',
    storageBucket: 'companies-tasks.appspot.com',
    measurementId: 'G-PWBXJSMDE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK2vLcL2ehdz-B-MNNKJf7gjRdoxw4JN8',
    appId: '1:706621538915:android:de02cf6e68646dbd452e56',
    messagingSenderId: '706621538915',
    projectId: 'companies-tasks',
    storageBucket: 'companies-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnvr7wPF8rmFoWuq_dJJH6BbGMkOWth0A',
    appId: '1:706621538915:ios:74bc3ea39a712fd5452e56',
    messagingSenderId: '706621538915',
    projectId: 'companies-tasks',
    storageBucket: 'companies-tasks.appspot.com',
    iosBundleId: 'com.example.companiesTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnvr7wPF8rmFoWuq_dJJH6BbGMkOWth0A',
    appId: '1:706621538915:ios:74bc3ea39a712fd5452e56',
    messagingSenderId: '706621538915',
    projectId: 'companies-tasks',
    storageBucket: 'companies-tasks.appspot.com',
    iosBundleId: 'com.example.companiesTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfYJcUWjv-gfNCxNZJ54rU6OhfSYNhRL0',
    appId: '1:706621538915:web:bee733f04b386419452e56',
    messagingSenderId: '706621538915',
    projectId: 'companies-tasks',
    authDomain: 'companies-tasks.firebaseapp.com',
    storageBucket: 'companies-tasks.appspot.com',
    measurementId: 'G-K1YLQM22VG',
  );

}